import { motion } from 'framer-motion';
const asset=(name:string)=>`${import.meta.env.BASE_URL}assets/${name}`;
export function Scene6(){return <motion.div className="absolute inset-0 overflow-hidden" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.7}}>
  <div className="absolute inset-0 bg-[#0b0c0b]"/><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_50%_30%,rgba(190,166,95,.12),transparent_36%),linear-gradient(180deg,#11120f_0%,#0a0b0a_100%)]"/>
  <motion.div className="screenshot-shell absolute left-[7vw] top-[8vh] h-[70vh] w-[51vw] overflow-hidden rounded-[.7vw]" initial={{opacity:0,y:20,scale:1.04}} animate={{opacity:[0,1,1,0],y:0,scale:1}} transition={{duration:3.25,times:[0,.18,.72,1]}}><img src={asset('chek-04-passed.jpg')} alt="CHEK compliant result and signed vault" className="h-full w-full object-contain object-center"/></motion.div>
  <motion.div className="absolute right-[7vw] top-[18vh] w-[27vw]" initial={{opacity:0,x:20}} animate={{opacity:[0,1,1,0],x:0}} transition={{duration:3.2,times:[0,.2,.72,1]}}><div className="micro-label mb-[1.5vh] text-[#9dc2ac]">06 / VERIFIED</div><h2 className="m-0 font-[var(--font-display)] text-[4.8vw] font-medium leading-[.88] tracking-[-.07em] text-[#eee8dc]">100%</h2><div className="mt-[1.7vh] flex items-center gap-[.75vw]"><div className="h-[.5vw] w-[.5vw] rounded-full bg-[#8db79e] shadow-[0_0_1vw_rgba(141,183,158,.7)]"/><span className="font-[var(--font-mono)] text-[.73vw] tracking-[.14em] text-[#9fc2ad]">VERIFIED / GATE PASSED</span></div><p className="mt-[3vh] max-w-[21vw] text-[.82vw] leading-[1.5] text-[#aaa99f]">Only the independently verified result moves forward. The signed trail remains.</p></motion.div>
  <motion.div className="absolute inset-0 flex items-center justify-center bg-[#090a09]" initial={{opacity:0}} animate={{opacity:[0,0,1,1]}} transition={{duration:4.3,times:[0,.68,.82,1]}}>
    <motion.div className="relative flex flex-col items-center" initial={{opacity:0,scale:.88}} animate={{opacity:[0,0,1,1],scale:[.88,.88,1,1]}} transition={{duration:4.35,times:[0,.72,.86,1]}}><div className="mb-[1.2vh] flex h-[4.2vw] w-[4.2vw] items-center justify-center border border-[#d5bb70]/70"><div className="h-[2.2vw] w-[2.2vw] rotate-45 border border-[#d5bb70]/80"/></div><div className="final-wordmark font-[var(--font-display)] text-[3.8vw] font-medium text-[#e8dfc9]">CHEK</div><div className="mt-[1.8vh] font-[var(--font-mono)] text-[.72vw] tracking-[.25em] text-[#c8b779]">GOVERNANCE FROM AI TO SILICON</div><div className="mt-[2.2vh] font-[var(--font-mono)] text-[.54vw] tracking-[.22em] text-[#87887e]">INDEPENDENT VERIFICATION / PRESERVED EVIDENCE</div></motion.div>
  </motion.div>
</motion.div>}
